Add 'aws-sdk' installation instructions
jooycar/aws-cloudwatch-metric-count pull request #6
Opened 2021-12-01 00:09 UTC by topher200

Without installing the sdk first I get this error:

```
$ node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
```

After installing the sdk everything works fine!

2022-02-04 13:06 UTC, Alynva commented
In most NodeJs projects, you have to install de dependencies of it with `npm install` before running the project. The `aws-sdk` is already listed as dependency on the `package.json`, so no need to specify witch dependency you have to install, just do the `npm install` and you're good to go. But I agree that is better to add this in the README, just don't need the `aws-sdk` in it.

2022-03-28 16:04 UTC, gvasquez95 requested changes

2022-03-28 16:04 UTC, gvasquez95 commented on README.md
> +    npm install aws-sdk
the `aws-sdk` part is redundant, `npm instal`l is enough

2022-05-17 19:54 UTC, millerick commented
I rolled these changes into another update to the README I thought of
https://github.com/jooycar/aws-cloudwatch-metric-count/pull/10

2022-05-17 19:54 UTC, millerick commented
I rolled these changes into another update to the README I thought of
https://github.com/jooycar/aws-cloudwatch-metric-count/pull/10

2022-05-31 18:40 UTC, closed without merging